### extrato
GET http://localhost:5000/clientes/1/extrato

### debitar
POST  http://localhost:9999/clientes/1/transacao

{
    "valor": 10000,
    "tipo" : "c",
    "descricao" : "descricaos"
}

### debitar
POST  http://localhost:5000/clientes/1/transacao

{"valor": 1, "tipo": "c", "descricao": "toma"}

### debitar
POST  http://localhost:5000/clientes/1/transacao

{"valor": 1, "tipo": "d", "descricao": "devolve"}